### PR TITLE
adding retry logic as report did not run-DTSPO-18001

### PR DESCRIPTION
**Pull request by ConnorOKane-Kainos**
### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

### CODE REVIEW

**Review by thomast1906 — CHANGES_REQUESTED** [review]
Why the retrry? what was yesterdays error?

**Comment by ConnorOKane-Kainos** [comment]
> Why the retrry? what was yesterdays error?

I implemented this retry logic as yesterdays report failed. I seen Danny had done something similar here before with this one - https://github.com/hmcts/postgresql-cron-jobs/commit/d297ca0bbc4bf8c6eec81d3fbff27b9a1fb78cfe#diff-a025ee79e596f407773e2590fec9809446817beefb8a5ec5bbdaaee19a3d5bd1R213

I can grab the full error from the reported of the ticket?

**Comment by ConnorOKane-Kainos** [comment]
Hey Thomas,

Here is the pipeline that was failing - [https://dev.azure.com/hmcts/PlatformOperations/_build/results?buildId=593867&view=l[…]-9ee4-bcf258bdad59&t=4d44d7fd-f678-5717-63e7-f87fa753a9f4&l=42](https://dev.azure.com/hmcts/PlatformOperations/_build/results?buildId=593867&view=logs&j=cf3d79ee-1764-5434-9ee4-bcf258bdad59&t=4d44d7fd-f678-5717-63e7-f87fa753a9f4&l=42)

On line 42 it seems to have been a connection time out: failed: Connection timed out

**Comment by ConnorOKane-Kainos** [comment]
Retry logic isnt required

**Review by danielwilsonkainos — APPROVED** [review]

**Review by thomast1906 — APPROVED** [review]

**Pull request merged**
